<#
.SYNOPSIS
  Exports remediated GPO backups and children GPOs that can be imported
  into Active Directory and linked to OUs.

.DESCRIPTION
  After the diff review, the user has a set of "selected" changes. This
  module:

    1. Takes the master template settings + the reviewed diffs.
    2. Builds a GPO backup structure (GptTmpl.inf, audit.csv, Registry.pol,
       GPP XML) that applies only the selected remediation settings.
    3. If the original GPO has child GPOs at child OUs, it generates
       separate backup folders for each child so they can be imported
       independently.
    4. Produces an import script (Import-RemediatedGPOs.ps1) the admin
       can run on a domain controller to create and link the GPOs.

  Requires: GroupPolicy module (RSAT) for final import; the export
  itself is file-only and can run anywhere.
#>

#requires -Version 5.1

#region ── GPO backup folder scaffolding ──────────────────────────────

function New-GpoBackupFolder {
    <#
    .SYNOPSIS  Create the standard GPO backup folder skeleton.
    .PARAMETER BasePath   Root output directory.
    .PARAMETER GpoName    Display name for the GPO (used as folder name).
    .PARAMETER GpoGuid    Optional GUID; a new one is generated if omitted.
    .OUTPUTS   PSCustomObject with paths: Root, MachineDir, UserDir, Guid.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$BasePath,
        [Parameter(Mandatory)][string]$GpoName,
        [string]$GpoGuid
    )

    if (-not $GpoGuid) { $GpoGuid = [guid]::NewGuid().Guid }

    $safeName = $GpoName -replace '[\\/:*?"<>|]', '_'
    $root     = Join-Path $BasePath $safeName
    $guidDir  = Join-Path $root "{$GpoGuid}"
    $machDir  = Join-Path $guidDir 'DomainSysvol\GPO\Machine'
    $userDir  = Join-Path $guidDir 'DomainSysvol\GPO\User'

    foreach ($d in @($root, $guidDir, $machDir, $userDir)) {
        if (-not (Test-Path $d)) { New-Item -Path $d -ItemType Directory -Force | Out-Null }
    }

    # Backup.xml metadata
    $backupXml = @"
<?xml version="1.0" encoding="utf-8"?>
<GroupPolicyBackupScheme bkp:version="2.0"
  bkp:type="GroupPolicyBackup"
  xmlns:bkp="http://www.microsoft.com/GroupPolicy/GPOOperations/Manifest"
  xmlns="http://www.microsoft.com/GroupPolicy/GPOOperations">
  <GroupPolicyObject>
    <GroupPolicyCoreSettings>
      <ID><![CDATA[{$GpoGuid}]]></ID>
      <Domain></Domain>
      <SecurityDescriptor></SecurityDescriptor>
      <DisplayName><![CDATA[$GpoName]]></DisplayName>
      <Options>0</Options>
      <UserVersionDirectory>0</UserVersionDirectory>
      <UserVersionSysvol>0</UserVersionSysvol>
      <MachineVersionDirectory>0</MachineVersionDirectory>
      <MachineVersionSysvol>0</MachineVersionSysvol>
    </GroupPolicyCoreSettings>
  </GroupPolicyObject>
</GroupPolicyBackupScheme>
"@
    $backupXml | Set-Content -Path (Join-Path $guidDir 'Backup.xml') -Encoding UTF8

    # bkupInfo.xml
    $bkupInfo = @"
<?xml version="1.0" encoding="utf-8"?>
<BackupInst xmlns="http://www.microsoft.com/GroupPolicy/GPOOperations/Manifest">
  <GPOGuid><![CDATA[{$GpoGuid}]]></GPOGuid>
  <GPODomain></GPODomain>
  <GPODomainGuid></GPODomainGuid>
  <GPODomainController></GPODomainController>
  <BackupTime>$(Get-Date -Format 'yyyy-MM-ddTHH:mm:ss')</BackupTime>
  <ID><![CDATA[{$([guid]::NewGuid().Guid)}]]></ID>
  <Comment>Generated by GPO Policy Audit tool</Comment>
  <GPODisplayName><![CDATA[$GpoName]]></GPODisplayName>
</BackupInst>
"@
    $bkupInfo | Set-Content -Path (Join-Path $guidDir 'bkupInfo.xml') -Encoding UTF8

    return [PSCustomObject]@{
        Root       = $root
        GuidDir    = $guidDir
        MachineDir = $machDir
        UserDir    = $userDir
        Guid       = $GpoGuid
        GpoName    = $GpoName
    }
}

#endregion

#region ── Write GptTmpl.inf ──────────────────────────────────────────

function Export-SecurityTemplate {
    <#
    .SYNOPSIS  Write security template settings to GptTmpl.inf format.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][PSCustomObject[]]$Settings,
        [Parameter(Mandatory)][string]$OutputPath
    )

    $sections = [ordered]@{}
    foreach ($s in $Settings) {
        if ($s.Category -ne 'Security Template') { continue }
        $sec = $s.SubCategory
        if (-not $sections.Contains($sec)) { $sections[$sec] = [System.Collections.Generic.List[string]]::new() }
        $sections[$sec].Add("$($s.SettingName) = $($s.SettingValue)")
    }

    if ($sections.Count -eq 0) { return }

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('[Unicode]')
    [void]$sb.AppendLine('Unicode=yes')
    [void]$sb.AppendLine('[Version]')
    [void]$sb.AppendLine('signature="$CHICAGO$"')
    [void]$sb.AppendLine('Revision=1')

    foreach ($sec in $sections.Keys) {
        [void]$sb.AppendLine("[$sec]")
        foreach ($line in $sections[$sec]) { [void]$sb.AppendLine($line) }
    }

    $parent = Split-Path $OutputPath -Parent
    $infDir = Join-Path $parent 'Microsoft\Windows NT\SecEdit'
    if (-not (Test-Path $infDir)) { New-Item -Path $infDir -ItemType Directory -Force | Out-Null }
    $infPath = Join-Path $infDir 'GptTmpl.inf'

    $sb.ToString() | Set-Content -Path $infPath -Encoding Unicode
    Write-Host "    GptTmpl.inf -> $infPath" -ForegroundColor Gray
}

#endregion

#region ── Write audit.csv ────────────────────────────────────────────

function Export-AuditPolicy {
    <#
    .SYNOPSIS  Write advanced audit policy settings to audit.csv format.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][PSCustomObject[]]$Settings,
        [Parameter(Mandatory)][string]$OutputPath
    )

    $auditSettings = $Settings | Where-Object { $_.Category -eq 'Advanced Audit Policy' }
    if (-not $auditSettings -or @($auditSettings).Count -eq 0) { return }

    $auditDir = Join-Path $OutputPath 'Microsoft\Windows NT\Audit'
    if (-not (Test-Path $auditDir)) { New-Item -Path $auditDir -ItemType Directory -Force | Out-Null }
    $csvPath = Join-Path $auditDir 'audit.csv'

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('Machine Name,Policy Target,Subcategory,Subcategory GUID,Inclusion Setting,Exclusion Setting,Setting Value')

    foreach ($s in $auditSettings) {
        $val = switch ($s.SettingValue) {
            'No Auditing'          { '0' }
            'Success'              { '1' }
            'Failure'              { '2' }
            'Success and Failure'  { '3' }
            default                { $s.SettingValue }
        }
        $inclExcl = if ($s.PSObject.Properties['IncExcl']) { $s.IncExcl } else { 'Include' }
        [void]$sb.AppendLine(",System,$($s.SettingName),,$inclExcl,,$val")
    }

    $sb.ToString() | Set-Content -Path $csvPath -Encoding UTF8
    Write-Host "    audit.csv -> $csvPath" -ForegroundColor Gray
}

#endregion

#region ── Master export orchestrator ─────────────────────────────────

function Export-RemediatedGPO {
    <#
    .SYNOPSIS
      Build GPO backup folder(s) from the reviewed diffs. Only selected
      (remediation) changes are written; deselected items are skipped.
    .PARAMETER ReviewedDiffs
      Diff array after interactive review (with Selected/RiskComment).
    .PARAMETER MasterSettings
      Full master template settings.
    .PARAMETER OutputFolder
      Where to create the GPO backup tree.
    .PARAMETER GpoNamePrefix
      Prefix for generated GPO names (e.g., "REMEDIATION -").
    .OUTPUTS
      Array of created backup folder info objects.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][PSCustomObject[]]$ReviewedDiffs,
        [Parameter(Mandatory)][PSCustomObject[]]$MasterSettings,
        [Parameter(Mandatory)][string]$OutputFolder,
        [string]$GpoNamePrefix = 'REMEDIATION -'
    )

    if (-not (Test-Path $OutputFolder)) { New-Item -Path $OutputFolder -ItemType Directory -Force | Out-Null }

    $selected = $ReviewedDiffs | Where-Object { $_.Selected -eq $true }
    if (-not $selected -or @($selected).Count -eq 0) {
        Write-Host "`n  No selected changes to export." -ForegroundColor DarkGray
        return @()
    }

    Write-Host "`n--- Exporting Remediated GPOs ---" -ForegroundColor Cyan

    # Group by GPO name (so each GPO gets its own backup folder)
    $grouped = $selected | Group-Object GpoName
    $createdBackups = [System.Collections.Generic.List[PSCustomObject]]::new()

    foreach ($g in $grouped) {
        $gpoName    = "$GpoNamePrefix $($g.Name)"
        $gpoGuid    = $null

        # Try to use the original GUID if available
        $firstDiff = $g.Group | Select-Object -First 1
        if ($firstDiff.GpoGuid) { $gpoGuid = $firstDiff.GpoGuid }

        Write-Host "  Creating backup: $gpoName" -ForegroundColor Yellow

        $backup = New-GpoBackupFolder -BasePath $OutputFolder -GpoName $gpoName -GpoGuid $gpoGuid

        # Build the settings collection for this GPO from master template,
        # filtered to only the keys that were selected for remediation
        $selectedKeys = [System.Collections.Generic.HashSet[string]]::new()
        foreach ($d in $g.Group) { [void]$selectedKeys.Add($d.Key) }

        $masterDict = @{}
        foreach ($s in $MasterSettings) {
            $key = "$($s.Category)|$($s.SubCategory)|$($s.SettingName)"
            $masterDict[$key] = $s
        }

        $gpoSettings = [System.Collections.Generic.List[PSCustomObject]]::new()
        foreach ($key in $selectedKeys) {
            if ($masterDict.ContainsKey($key)) {
                $gpoSettings.Add($masterDict[$key])
            }
        }

        # Write each artefact type
        Export-SecurityTemplate -Settings $gpoSettings -OutputPath $backup.MachineDir
        Export-AuditPolicy     -Settings $gpoSettings -OutputPath $backup.MachineDir

        $createdBackups.Add($backup)
    }

    # Generate the import helper script
    $importScript = Build-ImportScript -Backups $createdBackups -OutputFolder $OutputFolder
    Write-Host "  Import script: $importScript" -ForegroundColor Green

    # Generate the risk acceptance report
    $deselected = $ReviewedDiffs | Where-Object { $_.Selected -eq $false }
    if ($deselected -and @($deselected).Count -gt 0) {
        $riskPath = Join-Path $OutputFolder 'RiskAcceptanceReport.csv'
        $deselected | Select-Object GpoName, SettingName, Category, SubCategory, BaselineValue, GpoValue, RiskComment |
            Export-Csv -Path $riskPath -NoTypeInformation -Encoding UTF8
        Write-Host "  Risk acceptance report: $riskPath" -ForegroundColor DarkYellow
    }

    Write-Host "`n--- Export Complete ---" -ForegroundColor White
    Write-Host "  Backups created: $($createdBackups.Count)" -ForegroundColor Cyan

    return $createdBackups
}

#endregion

#region ── Import script generator ────────────────────────────────────

function Build-ImportScript {
    <#
    .SYNOPSIS
      Generate a PowerShell script that imports the remediated GPO
      backups into AD and optionally links them.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][PSCustomObject[]]$Backups,
        [Parameter(Mandatory)][string]$OutputFolder
    )

    $scriptPath = Join-Path $OutputFolder 'Import-RemediatedGPOs.ps1'

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine(@'
<#
.SYNOPSIS
  Import remediated GPO backups generated by the GPO Policy Audit tool.

.DESCRIPTION
  This script imports each GPO backup folder into Active Directory. After
  import, you can link them to the appropriate OUs using the Group Policy
  Management Console or the New-GPLink cmdlet.

  Run this on a machine with RSAT Group Policy Management installed and
  appropriate domain admin rights.

.PARAMETER DomainDnsName
  Target domain. Defaults to the computer's domain.

.PARAMETER LinkToOU
  Optional: OU distinguished name to link each imported GPO to.

.PARAMETER WhatIf
  Preview without making changes.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$DomainDnsName,
    [string]$LinkToOU
)

$ErrorActionPreference = 'Stop'
Import-Module GroupPolicy -ErrorAction Stop

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
'@)

    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('$backups = @(')

    foreach ($b in $Backups) {
        $relPath = $b.Root.Replace($OutputFolder, '$scriptDir').Replace('\', '\\')
        [void]$sb.AppendLine("    @{ Name = '$($b.GpoName)'; Guid = '$($b.Guid)'; Path = `"$relPath`" }")
    }

    [void]$sb.AppendLine(')')
    [void]$sb.AppendLine('')

    [void]$sb.AppendLine(@'
$domSplat = @{}
if ($DomainDnsName) { $domSplat['Domain'] = $DomainDnsName }

foreach ($bk in $backups) {
    Write-Host "Importing: $($bk.Name)" -ForegroundColor Cyan

    if ($PSCmdlet.ShouldProcess($bk.Name, 'Import-GPO')) {
        try {
            Import-GPO -BackupId $bk.Guid -Path $bk.Path -TargetName $bk.Name -CreateIfNeeded @domSplat
            Write-Host "  Imported successfully." -ForegroundColor Green

            if ($LinkToOU) {
                New-GPLink -Name $bk.Name -Target $LinkToOU @domSplat -ErrorAction Stop
                Write-Host "  Linked to: $LinkToOU" -ForegroundColor Green
            }
        } catch {
            Write-Warning "  Failed: $($_.Exception.Message)"
        }
    }
}

Write-Host "`nDone. Review imported GPOs in Group Policy Management Console." -ForegroundColor White
'@)

    $sb.ToString() | Set-Content -Path $scriptPath -Encoding UTF8
    return $scriptPath
}

#endregion

Export-ModuleMember -Function @(
    'Export-RemediatedGPO',
    'New-GpoBackupFolder',
    'Export-SecurityTemplate',
    'Export-AuditPolicy',
    'Build-ImportScript'
)
